stages:          # List of stages for jobs, and their order of execution
  - test
  - build
  - deploy

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: openjdk:11
  script:
    - echo "Running unit tests..."
    - ./gradlew test

# You can add another job in the same stage. Both jobs will run at the same time.

build-job:       # This job runs in the build stage, which runs first..
  stage: build
  image: docker:20.10
  services:
    - docker:20.10-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "Logging in to Dockerhub..."
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - echo "Building the docker image from Dockerfile..."
    - docker build -t api-postable:1.0 .
    - echo "Pushing to Dockerhub..."
    - docker tag api-postable:1.0 axelallain/api-postable:1.0
    - docker push axelallain/api-postable:1.0

deploy-dev-job:
  stage: deploy
  before_script:
    - chmod 400 $SSH_PRIVATE_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $SSH_USER@$DEV_ENV_IP_ADDRESS "
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD &&
        docker ps -aq | xargs -r docker stop &&
        docker ps -aq | xargs -r docker rm &&
        docker network create postablenet
        docker run -d -p 5432:5432 -e POSTGRES_USER=$DB_USER -e POSTGRES_PASSWORD=$DB_PASSWORD -e POSTGRES_DB=$DB_NAME postgres &&
        docker run -d -p 8080:8080 axelallain/api-postable:1.0"
