---

- name: Install and run Docker
  hosts: api
  become: yes
  become_user: root
  tasks:
    - name: Add Docker repository
      ansible.builtin.yum_repository:
        name: "docker repository"
        description: "This repository is required to install Docker."
        baseurl: "https://download.docker.com/linux/centos/docker-ce.repo"
        state: present
        enabled: yes

    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: latest
        update_cache: true

    - name: Start Docker service
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started
